title       = "vietnamworks"
baseURL     = "https://vietnamworks-cli.tamnd.com/"
description = "A command line for vietnamworks."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/vietnamworks-cli"
